server.port: 9998

spring:
  application:
    name: clicker-kombat
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/clicker_kombat
    username: postgres
    password: 12qw23qw
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: INFO
    root: info

jwt:
  private.key: classpath:private.pem
  public.key: classpath:public.pem
  token.expiry: 86400
  refresh-token.expiry: 1209600

gameplay:
  coef:
    faction.profit.multiplier: 0.75