CREATE TABLE IF NOT EXISTS characters
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name VARCHAR(255),
    player_id      BIGINT,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_players_id ON characters (player_id);

CREATE TABLE IF NOT EXISTS players
(
    id                BIGINT NOT NULL,
    username          VARCHAR(255),
    login             VARCHAR(255),
    token             VARCHAR(255),
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    last_online       TIMESTAMP WITHOUT TIME ZONE,
    is_active         BOOLEAN,
    CONSTRAINT pk_players PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS udx_players_username ON players (username);

CREATE TABLE IF NOT EXISTS users
(
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    enabled  BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

create table if not exists authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    constraint delete_user_cascade foreign key (username) references users (username) on delete cascade
);
create unique index if not exists udx_auth_username on authorities (username, authority);


ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id);

CREATE TABLE IF NOT EXISTS factions
(
    id                          SMALLINT NOT NULL,
    name                        VARCHAR(255),
    description                 VARCHAR(255),
    profit                      INT,
    profit_balancing_multiplier REAL,
    is_active                   BOOLEAN,
    CONSTRAINT pk_faction PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS character_info
(
    character_id BIGINT NOT NULL,
    faction_id   BIGINT,
    faction_name VARCHAR(255),
    is_active    BOOLEAN,
    profit       INTEGER,
    CONSTRAINT pk_character_info PRIMARY KEY (character_id)
);

CREATE TABLE IF NOT EXISTS character_upgrades
(
    character_id BIGINT NOT NULL,
    up_coins     BIGINT,
    upgrades     jsonb,
    CONSTRAINT pk_character_upgrades PRIMARY KEY (character_id)
);

CREATE TABLE IF NOT EXISTS character_xp
(
    id                  BIGINT NOT NULL,
    character_id        BIGINT,
    level               SMALLINT,
    current_xp          BIGINT,
    all_xp              BIGINT,
    xp_requirement      BIGINT,
    xp_until_next_level BIGINT,
    CONSTRAINT pk_character_xp PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS refresh_token
(
    token    uuid,
    username VARCHAR(255),
    expiry_date timestamptz,
    CONSTRAINT pk_refresh_token PRIMARY KEY (token)
);

CREATE VIEW faction_profits AS
SELECT faction_id,
       faction_name,
       is_active,
       SUM(profit)         AS profit_sum,
       count(character_id) AS character_count
FROM character_info
GROUP BY faction_id, faction_name, is_active