CREATE TABLE characters
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name      VARCHAR(255),
    faction             VARCHAR(255),
    level               SMALLINT,
    up_coins            BIGINT,
    upgrades            jsonb,
    all_xp              BIGINT,
    current_xp          BIGINT,
    xp_requirement      BIGINT,
    xp_until_next_level BIGINT,
    tg_id               BIGINT,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_players_id ON characters (tg_id);

CREATE TABLE players
(
    tg_id             BIGINT NOT NULL,
    username          VARCHAR(255),
    token             VARCHAR(255),
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    last_online       TIMESTAMP WITHOUT TIME ZONE,
    is_active         BOOLEAN,
    CONSTRAINT pk_players PRIMARY KEY (tg_id)
);

CREATE INDEX IF NOT EXISTS udx_players_username ON players (username);

CREATE TABLE users
(
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_TG FOREIGN KEY (tg_id) REFERENCES players (tg_id);